# Generated by Django 3.0.5 on 2020-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
